{{- if not .Values.customSecretName }}
{{- if not .Values.personalAPIKey }}
  {{ fail "personalAPIKey must be set when customSecretName is not provided" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "newrelic.common.naming.fullname" . }}
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
type: Opaque
stringData:
  personalAPIKey: {{ .Values.personalAPIKey | quote }}
{{- end }}
