apiVersion: v2
description: A Helm chart to deploy the New Relic Kubernetes Metrics Adapter.
name: newrelic-k8s-metrics-adapter
version: 0.7.9
appVersion: 0.2.0
home: https://hub.docker.com/r/newrelic/newrelic-k8s-metrics-adapter
sources:
  - https://github.com/newrelic/newrelic-k8s-metrics-adapter
  - https://github.com/newrelic/newrelic-k8s-metrics-adapter/tree/main/charts/newrelic-k8s-metrics-adapter
engine: gotpl
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg

dependencies:
  - name: common-library
    version: 1.1.0
    repository: "https://helm-charts.newrelic.com"

maintainers:
  - name: alvarocabanas
  - name: carlossscastro
  - name: gsanchezgavier
  - name: kang-makes
  - name: marcsanmi
  - name: paologallinaharbur
  - name: roobre
  - name: sigilioso
keywords:
  - infrastructure
  - newrelic
  - monitoring
