{{- if (and (not .Values.customTLSCertificate) (not .Values.certManager.enabled)) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "common.naming.fullname" . }}-apiservice
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ template "common.naming.name" . }}
    {{- include "common.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "common.naming.fullname" . }}-apiservice
subjects:
  - kind: ServiceAccount
    name: {{ include "common.serviceAccount.name" . }}-apiservice
    namespace: {{ .Release.Namespace }}
{{- end }}
